spring:
  datasource:
    url: jdbc:mysql://rootimpact3.cp8awcg64bme.ap-northeast-2.rds.amazonaws.com:3306/bloom?useSSL=true&serverTimezone=UTC
    username: admin
    password: RootImpact3
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      idle-timeout: 30000
      connection-timeout: 60000
      max-lifetime: 1800000
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger

  cloud:
    gateway:
      routes:
        - id: login-service
          uri: http://13.125.19.104:8080  # 실제 API 서버 주소
          predicates:
            - Path=/api/users/login  # 클라이언트에서 요청할 경로
          filters:
            - AddRequestHeader=X-Request-Foo, Bar  # 요청에 헤더를 추가할 수 있음
