spring:
  datasource:
    url: jdbc:mysql://rootimpact3.cp8awcg64bme.ap-northeast-2.rds.amazonaws.com:3306/bloom?useSSL=true&serverTimezone=UTC
    username: admin
    password: RootImpact3
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      idle-timeout: 30000
      connection-timeout: 60000
      max-lifetime: 1800000
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger

management:
  endpoints:
    web:
      exposure:
        include: health